name: Code quality Whiskers-web Package

on:
  push:
    branches: [main]
    paths:
      - "apps/whiskers-web/**"
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./apps/whiskers-web
